### ISSUE TITLE
Runtime version

### ISSUE THREAD

**Issue by adds68** [kujeger/flatpak-gog#5]
Hi,

First of all thanks for this great work! :)

I have been helping to build the new freedesktop-sdk runtime over at: 
 * https://gitlab.com/freedesktop-sdk/freedesktop-sdk

I noticed that you are using the gnome runtime to build you base app, and was curious what was needed from the gnome runtime, i tried to build this app against the latest 18.08 freedesktop runtime and built successfully?

I'm also curious as to why the Template app needs to use the gnome runtime?

Could these not just depends directly on freedesktop-sdk, we are happy to also try and include any new dependencies you may need to make building this easier.

**Comment by Pixelnarium** [comment]
It was mentioned [here]( https://github.com/kujeger/flatpak-gog/commit/ab3c8128fa88a42ffd46f11d849cbae69a4b4ee5 ). I don't know what games need GNOME stuff but I don't have all of them. Maybe some launchers?

Like I said in issue #4 I am already using the freedesktop runtime in a personal "fork". Except for an already reported (and fixed in master) bug in SDL in combination with Starbound everything I tried works with the 18.08 runtime (+udev and glu from shared-modules).

So far I tried:
Starbound (works with 1.6 until the fix lands in 18.08), FTL Advanced, Stardew Valley, DEFCON, Thimbleweed Park.
Broforce starts but this is also a game that writes to it's game directory. Needs some overwrites/configs to work well. I will look at it when I have time for that.

**Comment by kujeger** [comment]
Thanks!

If I remember right, some games had a launcher that depended on some GTK/Gnome stuff (note to self, maybe specify things like that in the commit text next time...)

I'll try out the games I had in the archlist at that commit (using the newer freedesktop runtime) when I get the time, and report back

**Comment by kujeger** [comment]
Tested various games and they worked fine with the freedesktop runtime, so I've changed it with 9a4626e. Thanks!
