### ISSUE TITLE
Misleading documentation for DLC building withh --extra

### ISSUE THREAD

**Issue by mscherer** [kujeger/flatpak-gog#9]
I am using json-maker.py on Hacknet and its DLC. The documentation in --help seems to imply that --extra is supposed to go before the final argument:

    $ json-maker.py -h
    usage: json-maker.py [-h] [--name NAME] [--template TEMPLATE]
                         [--startoverride STARTOVERRIDE]
                         [--configureoverride CONFIGUREOVERRIDE]
                         [--extra [EXTRA [EXTRA ...]]] [--branch BRANCH]
                         [--arch {auto,i386,x86_64}] [--output OUTPUT]
                         installer

However, that's not the case:

    $ json-maker.py  --extra dlc/hacknet_labyrinths/hacknet_labyrinths_dlc_en_5_069_15083.sh hacknet_en_5_069_15083.sh
    usage: json-maker.py [-h] [--name NAME] [--template TEMPLATE]
                         [--startoverride STARTOVERRIDE]
                         [--configureoverride CONFIGUREOVERRIDE]
                         [--extra [EXTRA [EXTRA ...]]] [--branch BRANCH]
                         [--arch {auto,i386,x86_64}] [--output OUTPUT]
                         installer
    json-maker.py: error: too few arguments

Should the documentation be fixed, or the parsing of the --extra switch be changed ?

**Comment by kujeger** [comment]
Yeah, the behaviour of argparse is a bit weird here -- an option that accepts multiple arguments (e.g. --extra dlc1.sh dlc2.sh) has to appear after any positional arguments, like this: `./json-maker.py installer.sh --extra dlc1.sh dlc2.sh`

https://bugs.python.org/issue9338

I'll look into changing it so that it's instead used multiple times: `--extra dlc1.sh --extra dlc2.sh`
